[project]
org-name = "ballerinax"
version = "0.9.0"
authors = ["Ballerina"]
repository = "https://github.com/ballerina-platform/module-twilio"
keywords = ["twilio", "sms", "call", "otp", "whatsapp"]
license = ["Apache-2.0"]
