[package]
org = "ballerinax"
name = "module_ballerinax_twilio"
version = "0.9.2"
authors = ["Ballerina"]
repository = "https://github.com/ballerina-platform/module-ballerinax-twilio"
keywords = ["twilio", "sms", "call", "otp", "whatsapp"]
license = ["Apache-2.0"]

[build-options]
observabilityIncluded = true